### ISSUE TITLE
does pnorm work with new numpy?

### ISSUE THREAD

**Issue by argriffing** [cvxgrp/cvxpy#209]
In the cvxpy nosetests I'm getting errors like

> TypeError: ufunc 'power' output (typecode 'O') could not be coerced to provided output parameter (typecode 'd') according to the casting rule ''same_kind''

with a development version of numpy 1.10.0, which I guess is due to a problem with an interaction between numpy ufuncs and ndarrays of python fractions. Maybe this is a regression (bug) in numpy or maybe it's a cvxpy problem, or possibly a problem with my own system.

**Comment by argriffing** [comment]
In general I think the linear algebra functions in numpy and scipy can be used safely only with traditional BLAS types (32/64 bit float and 64/128 bit complex). Not so much with the python `fractions.Fraction` type.

**Comment by argriffing** [comment]
The relevant numpy change is in version 1.10 where the default casting has been changed to `same_kind`.
http://docs.scipy.org/doc/numpy-dev/reference/ufuncs.html#ufunc
Basically this makes numpy even less friendly to non-BLAS-like data types, and in particular breaks some usage of `fractions.Fraction` in cvxpy. I think this is a deliberate change in numpy and that cvxpy would have to work around it :/

**Comment by SteveDiamond** [comment]
Thanks for pointing this issue out! I believe I fixed it with the latest patch to master. Would you mind trying the nosetests again with the new branch of numpy?

**Comment by argriffing** [comment]
It still doesn't work for me, I think `return np.linalg.norm(values, self.p)` needs the same treatment as https://github.com/cvxgrp/cvxpy/commit/b0644d4f054445bc1577d328a5c77a828f3afaf0.

**Comment by SteveDiamond** [comment]
Ok, I fixed ``pnorm``. It should work now.

**Comment by argriffing** [comment]
Yes `nosetests cvxpy` passes for me now.
```
..........................
----------------------------------------------------------------------
Ran 2506 tests in 31.290s

OK
```
