### ISSUE TITLE
conda install (Python 3.6)

### ISSUE THREAD

**Issue by SteliosStefanatos** [cvxgrp/cvxpy#332]
I am on Linux, trying to install cvxpy with Anaconda (Python 3.6). Following the install guide,

 `conda install -c cvxgrp cvxpy` 

returns 

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - cvxpy
  - python 3.6*
```

**Comment by sschnug** [comment]
Without trying it: 

It just means, that anaconda thinks, that cvxpy and python 3.6 are not compatible. 

As i don't see this python-version limitation in cvxpy's setup scripts, i think it's some limitation coming from anaconda's build.

There are basically two approaches here:
- use python 3.5 (e.g. with some virtualenvironment)
- install cvxpy with ```pip install cvxpy``` which will install it from the sources
    - you will of course need a system bringing all the build-tools needed
    - and make sure to run the tests!

**Comment by SteliosStefanatos** [comment]
@sschnug Thank you very much for the reply. I guess I will go with the python 3.5 option for the moment.

**Comment by sschnug** [comment]
@SteliosStefanatos  Yes try this. There should be no problem. But i recommend keeping this issue open as Anaconda's default Python-version seems to be 3.6 now.

For further debugging, this is what i obtain within some newly created Python 3.6 environment within Anaconda:

The following specifications were found to be in conflict:

      - certifi (target=certifi-2017.1.23-py36_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*|3.6*
      - cvxpy -> python *|2.7*|3.5*
      - pip (target=pip-9.0.1-py36_1.tar.bz2) -> python 2.7*|3.5*
      - pip (target=pip-9.0.1-py36_1.tar.bz2) -> setuptools
      - pip (target=pip-9.0.1-py36_1.tar.bz2) -> wheel
      - python 3.6*
      - setuptools (target=setuptools-33.1.0-py36_0.tar.bz2) -> certifi
      - setuptools (target=setuptools-33.1.0-py36_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*|3.6*
      - wheel (target=wheel-0.29.0-py36_0.tar.bz2) -> python 2.7*|3.3*|3.4*|3.5*|3.6*

I'm not sure how to read it, as in my mind, there should be no problem (if i read the * at cvxpy correctly) except for pip (which would not make much sense as it's up-to-date).

**Comment by SteveDiamond** [comment]
Hi everyone. @sschnug is quite right. I need to update the conda channel with cvxpy "compiled" for python 3.6.

**Comment by SteveDiamond** [comment]
I've pushed the latest cvxpy onto conda for all python versions.

**Comment by Garyfallidis** [comment]
Hi @SteveDiamond, I am still getting the same error. How can I install cvxpy with conda and python 3.6?
