### ISSUE TITLE
Maximize trace of a Hermitian matrix fails with objective must be real

### ISSUE THREAD

**Issue by Wulfsta** [cvxgrp/cvxpy#667]
**Description of the bug**
When trying to call Maximize on the trace of a Hermitian matrix CVXPY fails with a ValueError.

**To Reproduce**
```
import cvxpy as cvx
import numpy as np

c = [0, 1]
n = len(c)

# Create optimization variables.
f = cvx.Variable((n, n), hermitian=True)

# Create constraints.
constraints = [f >> 0]
for k in range(1, n):
    indices = [(i * n) + i - (n - k) for i in range(n - k, n)]
    constraints += [cvx.sum(cvx.vec(f)[indices]) == c[n - k]]

# Form objective.
obj = cvx.Maximize(c[0] - cvx.trace(f))

# Form and solve problem.
prob = cvx.Problem(obj, constraints)
sol = prob.solve()

print(sol)
print(f.value)
```

**Expected behavior**
The trace of a Hermitian matrix is real-valued, so this error should not be thrown. 

**Output**
```
Traceback (most recent call last):
  File "sdp_test.py", line 17, in <module>
    obj = cvx.Maximize(c[0] - cvx.trace(f))
  File "/usr/lib/python3.7/site-packages/cvxpy/problems/objective.py", line 46, in __init__
    % self.NAME)
ValueError: The 'maximize' objective must be real valued.
```

**Version**
 - OS: Arch Linux
 - CVXPY Version: 1.0.14

**Additional context**
I have also tried constraining this to real values in several ways, using both atoms and combinations of variables and constraints.

**Comment by duguyipiao** [comment]
I also came across similar problems before. It seems that cvxpy doesn't know `cvx.trace(f)` is real. You can try `cvx.real(cvx.trace(f))`.

**Comment by Wulfsta** [comment]
I did try this, it fails with a different error. I'm not by my machine right now, but I'll update later with that stack trace.

**Comment by Wulfsta** [comment]
I have tried this, but it yields a different error.

```
import cvxpy as cvx
import numpy as np

c = [0, 1]
n = len(c)

# Create optimization variables.
f = cvx.Variable((n, n), hermitian=True)

# Create constraints.
constraints = [f >> 0]
for k in range(1, n):
    indices = [(i * n) + i - (n - k) for i in range(n - k, n)]
    constraints += [cvx.sum(cvx.vec(f)[indices]) == c[n - k]]

# Form objective.
obj = cvx.Maximize(c[0] - cvx.real(cvx.trace(f)))

# Form and solve problem.
prob = cvx.Problem(obj, constraints)
sol = prob.solve()

print(sol)
print(f.value)
```

Errors with:
```
Traceback (most recent call last):
  File "sdp_test.py", line 21, in <module>
    sol = prob.solve()
  File "/usr/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 268, in solve
    return solve_func(self, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 381, in _solve
    data, inverse_data = self._solving_chain.apply(self)
  File "/usr/lib/python3.7/site-packages/cvxpy/reductions/chain.py", line 65, in apply
    problem, inv = r.apply(problem)
  File "/usr/lib/python3.7/site-packages/cvxpy/reductions/complex2real/complex2real.py", line 54, in apply
    constraint, inverse_data.real2imag, leaf_map)
  File "/usr/lib/python3.7/site-packages/cvxpy/reductions/complex2real/complex2real.py", line 112, in canonicalize_tree
    real_arg, imag_arg = self.canonicalize_tree(arg, real2imag, leaf_map)
  File "/usr/lib/python3.7/site-packages/cvxpy/reductions/complex2real/complex2real.py", line 112, in canonicalize_tree
    real_arg, imag_arg = self.canonicalize_tree(arg, real2imag, leaf_map)
  File "/usr/lib/python3.7/site-packages/cvxpy/reductions/complex2real/complex2real.py", line 112, in canonicalize_tree
    real_arg, imag_arg = self.canonicalize_tree(arg, real2imag, leaf_map)
  File "/usr/lib/python3.7/site-packages/cvxpy/reductions/complex2real/complex2real.py", line 117, in canonicalize_tree
    leaf_map)
  File "/usr/lib/python3.7/site-packages/cvxpy/reductions/complex2real/complex2real.py", line 139, in canonicalize_expr
    assert all(v is None for v in imag_args)
AssertionError
```

**Comment by duguyipiao** [comment]
**I think this should be viewed as a bug.**

But as a workaround, you can change
```python
    constraints += [cvx.sum(cvx.vec(f)[indices]) == c[n - k]]
```
to
```python
    constraints += [cvx.sum(cvx.vec(cvx.real(f))[indices]) == c[n - k]]
    constraints += [cvx.sum(cvx.vec(cvx.imag(f))[indices]) == 0]
```

**Comment by SteveDiamond** [comment]
Right, equality constraints for complex numbers aren't supported right now. I can add support. The initial issue with trace of a Hermitian matrix seems a bit niche, but maybe that should be supported.

**Comment by duguyipiao** [comment]
@SteveDiamond Is it related to #642 which also involves equality constraints for complex matrices?

**Comment by SteveDiamond** [comment]
I've fixed this on master. cvxpy wasn't properly handling the special indexing.

**Comment by vprusso** [comment]
I am still encountering the same error that the @Wulfsta was encountering despite using the `cvxpy` off of the master branch.

```
>>> import cvxpy as cvx
>>> print(cvx.__version__)
1.1.0a2
```

Version

OS: OSX (Mac)
CVXPY Version: 1.1.0a2
