### ISSUE TITLE
RuntimeWarning: overflow encountered in long_scalars   if self.max_big_small_squared < big*small**2:

### ISSUE THREAD

**Issue by cm76543** [cvxgrp/cvxpy#755]
**Describe the bug**
I am trying to run an integer programming optimization model on a relatively small dataset using cvxpy, and am running into the following error when I try to solve the problem:

"C:\Users\XXXX\AppData\Local\Continuum\Anaconda3-5.2.0\lib\site-packages\cvxpy\problems\problem.py:791: RuntimeWarning: overflow encountered in long_scalars if self.max_big_small_squared < big*small**2:"

I suspect this error is coming because python is handling my objective function as an int32, when maybe it should be an int64? It appears that int32 is the default datatype when taking the sum of a boolean vector, as I am in the objective function. Any ideas on how to solve this error? Including code below:

**To Reproduce**
import cvxpy as cv

#DEFINE THE SELECTION VARIABLE
selection = cv.Variable((113,33),boolean = True)

#DEFINE THE OBJECTIVE FUNCTION
num_columns_true = cv.sum(cv.max(selection, axis = 0))
  #think this is where the issue is coming from

#DEFINE THE CONSTRAINTS
one_true_per_row = cv.sum(selection, axis = 1) == 1
constraints = [one_true_per_row]

#DEFINE THE PROBLEM
problem = cv.Problem(cv.Minimize(num_columns_true), constraints = constraints)

#SOLVE THE PROBLEM
problem.solve(solver=cv.GLPK_MI, verbose = True)

**Expected behavior**
would not have expected this to throw an overflow error

**Output**
example code does get solved, with correct answer (1), but the output does throw an overflow error shown below. I am worried if I try to apply this code to a larger dataset, the runtime error will result in an incorrect answer:

C:\Users\XXXX\AppData\Local\Continuum\Anaconda3-5.2.0\lib\site-packages\cvxpy\problems\problem.py:791: RuntimeWarning: overflow encountered in long_scalars
  if self.max_big_small_squared < big*small**2:

**Version**
 - OS: 64-bit operating system, x64-based processor
 - CVXPY Version: 1.0.15

**Comment by SteveDiamond** [comment]
Sorry about that. I thought I had fixed this a while ago, but it must have been on a branch. This is fixed now on master.

**Comment by cm76543** [comment]
Hi Steve,

Thanks for the quick reply!  I just tried running the example code again, but am getting the same error still. Is there something else that I need to do to get the fix to come through?

**Comment by SteveDiamond** [comment]
Yes, you need to reinstall cvxpy from source. That's what I meant by "it's fixed on master."
